"""One-command M-Team preparation and browser form filling."""

from __future__ import annotations

import argparse
from pathlib import Path

from .mteam_fill import main as mteam_fill_main
from .prepare import main as prepare_main


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "一条命令完成 M-Team 资料准备并打开发布页填写。"
            "其余参数会原样交给 prepare，例如 --tmdb-id、--category、--screenshots。"
        )
    )
    parser.add_argument("input", type=Path, help="视频/ISO 文件或剧集目录")
    parser.add_argument("--profile-dir", type=Path, help="已登录的专用 Chrome 配置目录")
    parser.add_argument("--cookie-file", type=Path, help="M-Team Cookie 导出或请求头复制文件")
    parser.add_argument("--url", default="https://kp.m-team.cc/upload", help="M-Team 发布页地址")
    uploads = parser.add_mutually_exclusive_group()
    uploads.add_argument("--upload", dest="upload", action="store_true", help="上传种子和 4 张截图（默认）")
    uploads.add_argument("--no-upload", dest="upload", action="store_false", help="只填写字段，不上传文件")
    parser.set_defaults(upload=True)
    parser.add_argument("--yes", action="store_true", help="跳过发布页写入/上传前的确认")
    parser.add_argument("--keep-open", action="store_true", help="填表后保持 ChromeDriver 窗口打开")
    parser.add_argument("--login-timeout", type=int, default=600, help="等待手工登录的秒数；默认 600")
    return parser


def main(argv: list[str] | None = None) -> None:
    """Run ``prepare`` followed by ``mteam-fill`` with one user command."""
    parser = _parser()
    args, prepare_options = parser.parse_known_args(argv)

    # A torrent references the canonical names generated by prepare. Requiring
    # --apply here prevents a one-step run from creating a torrent that no
    # longer matches the files left on disk.
    if "--apply" not in prepare_options:
        parser.error("publish 为保证种子与文件名一致，必须传入 --apply")

    package_path = prepare_main([str(args.input), *prepare_options])
    if package_path is None:
        raise RuntimeError("prepare 未返回 M-Team 发布资料包")

    fill_args = [str(package_path)]
    if args.profile_dir:
        fill_args.extend(["--profile-dir", str(args.profile_dir)])
    if args.cookie_file:
        fill_args.extend(["--cookie-file", str(args.cookie_file)])
    fill_args.extend(["--url", args.url])
    if args.upload:
        fill_args.append("--upload")
    if args.yes:
        fill_args.append("--yes")
    if args.keep_open:
        fill_args.append("--keep-open")
    fill_args.extend(["--login-timeout", str(args.login_timeout)])
    mteam_fill_main(fill_args)


if __name__ == "__main__":
    main()
